version: '3.8'
services:

  minio:
    image: 'bitnami/minio:2022.2.5-debian-10-r0'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123